Bài tập 1: Numpy cơ bản

Câu 1:

In [2]:
 import numpy as np
 arr = np.arange(0, 10, 1)
 print(arr)

[0 1 2 3 4 5 6 7 8 9]


Câu 2:

In [3]:
arr = np.ones((3 , 3)) > 0
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [4]:
arr = np.ones((3 , 3), dtype = bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [5]:
arr = np.full((3, 3), fill_value = True, dtype = bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Câu 3:

In [6]:
import numpy as np
arr = np.arange(0, 10)
print(arr[arr%2 == 1])

[1 3 5 7 9]


Câu 4:

In [7]:
import numpy as np
arr = np.arange(0, 10)
arr[arr%2 == 1] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Câu 5:

In [8]:
import numpy as np
arr = np.arange(10)
arr_2d = arr.reshape(2, -1)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Câu 6:

In [11]:
import numpy as np
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate((arr1, arr2), axis = 0)
print("Result: \n",c)

Result: 
 [[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


Câu 7:

In [13]:
import numpy as np
arr1 = np.arange(10).reshape(2, -1)
arr2 = np.repeat(1, 10).reshape(2, -1)
c = np.concatenate((arr1, arr2), axis = 1)
print("C = ",c)

C =  [[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


Câu 8:

In [14]:
import numpy as np
arr = np.array([1, 2, 3])
print(np.repeat(arr, 3))
print(np.tile(arr, 3))

[1 1 1 2 2 2 3 3 3]
[1 2 3 1 2 3 1 2 3]


Câu 9:

In [16]:
import numpy as np
a = np.array([2, 6, 1, 9, 10, 3, 27])
index = np.where((a >= 5) & (a <= 10))
print("result",a[index])

result [ 6  9 10]


Câu 10:

In [17]:
import numpy as np

def maxx(x, y):
  if x >= y:
    return x
  else:
    return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

pair_max = np.vectorize(maxx,otypes=[float])
print(pair_max(a, b))

[6. 7. 9. 8. 9. 7. 5.]


Câu 11:

In [19]:
import numpy as np

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

print("Result", np.where(a<b, b, a))

Result [6 7 9 8 9 7 5]


Bài tập 2: Xử lý ảnh

Câu 12:

In [24]:
# Download image
!gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
img = mpimg.imread('/content/dog.jpeg')
gray_img_01 = (np.max(img, axis = 2) + np.min(img, axis = 2)) / 2
gray_img_01[0, 0]

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 44.9MB/s]


102.5

Câu 13:

In [25]:
# Download image
! gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
img = mpimg.imread('/content/dog.jpeg')
gray_img_02 = np.mean(img, axis = 2)
gray_img_02[0, 0]

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 67.0MB/s]


107.66666666666667

Câu 14:

In [26]:
# Download image
! gdown 1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB

import matplotlib.image as mpimg
img = mpimg.imread('/content/dog.jpeg')
gray_img_03 = 0.21 * img[:, :, 0] + 0.72 * img[:, :, 1] + 0.07 * img[:, :, 2]
gray_img_03[0, 0]

Downloading...
From: https://drive.google.com/uc?id=1i9dqan21DjQoG5Q_VEvm0LrVwAlXD0vB
To: /content/dog.jpeg
100% 33.7k/33.7k [00:00<00:00, 39.7MB/s]


126.22999999999999

Bài tập 3: Phân tích dữ liệu dạng bảng

In [28]:
# Download data
! gdown 1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq

import pandas as pd
df = pd.read_csv('/content/advertising.csv')
data = df.to_numpy()

Downloading...
From: https://drive.google.com/uc?id=1iA0WmVfW88HyJvTBSQDI5vesf-pgKabq
To: /content/advertising.csv
100% 4.06k/4.06k [00:00<00:00, 16.0MB/s]


Câu 15:

In [31]:
max_value = df['Sales'].max()
max_index = df['Sales'].idxmax()
print("Max:", max_value, "- Index:", max_index)

Max: 27.0 - Index: 175


Câu 16:

In [32]:
avarage_value = df['TV'].mean()
print(avarage_value)

147.0425


Câu 17:

In [34]:
count = df[df['Sales'] >= 20].shape[0]
print(count)

40


Câu 18:

In [35]:
filtered_df = df[df['Sales'] >= 15]
mean_radio = filtered_df['Radio'].mean()
print(mean_radio)

26.22293577981651


Câu 19:

In [36]:
mean_newspaper = df['Newspaper'].mean()
filtered_df = df[df['Newspaper'] >= mean_newspaper]
sum_sales = filtered_df['Sales'].sum()
print(sum_sales)

1405.1


Câu 20:

In [37]:
A = df['Sales'].mean()
scores = df['Sales'].apply(lambda x: 'Good' if x > A else ('Bad' if x < A else 'Average')).tolist()

print("Giá trị của scores[7:10]:", scores[7:10])

Giá trị của scores[7:10]: ['Bad', 'Bad', 'Good']


Câu 21:

In [38]:
mean_sales = df['Sales'].mean()

A = df['Sales'].iloc[(df['Sales'] - mean_sales).abs().argsort()[0]]

scores = df['Sales'].apply(lambda x: 'Good' if x > A else ('Bad' if x < A else 'Average')).tolist()

print("Giá trị của scores[7:10]:", scores[7:10])

Giá trị của scores[7:10]: ['Bad', 'Bad', 'Good']
