### Bài 1 Gradient Descent:

In [7]:
import numpy as np

In [12]:
def df_w(W):
    # Unpack w1 and w2 from W
    w1, w2 = W

    # Compute partial derivatives
    dw1 = 0.2 * w1  # ∂f/∂w1
    dw2 = 4 * w2  # ∂f/∂w2

    # Create gradient array
    dW = np.array([dw1, dw2])

    return dW

In [13]:
def sgd(W, dW, lr):
    W = W - lr*dW
    return W

In [14]:
def train_p1(optimizer, lr, epochs):
  # Initial point
    W = np.array([-5, -2], dtype=np.float32)
    # List of results
    results = [W.copy()]
    for epoch in range(epochs):
        # Compute the gradient at the current point
        dW = df_w(W)  # Assume `df_w` is defined to compute gradients

        # Update W using the optimizer
        W = optimizer(W, dW, lr)

        # Append the updated W to results
        results.append(W.copy())

    return results

In [15]:
train_p1(sgd, lr=0.4, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.6,  1.2]),
 array([-4.232, -0.72 ]),
 array([-3.89344,  0.432  ]),
 array([-3.5819648, -0.2592   ]),
 array([-3.29540762,  0.15552   ]),
 array([-3.03177501, -0.093312  ]),
 array([-2.78923301,  0.0559872 ]),
 array([-2.56609437, -0.03359232]),
 array([-2.36080682,  0.02015539]),
 array([-2.17194227, -0.01209324]),
 array([-1.99818689,  0.00725594]),
 array([-1.83833194, -0.00435356]),
 array([-1.69126538,  0.00261214]),
 array([-1.55596415, -0.00156728]),
 array([-1.43148702e+00,  9.40369969e-04]),
 array([-1.31696806e+00, -5.64221981e-04]),
 array([-1.21161061e+00,  3.38533189e-04]),
 array([-1.11468176e+00, -2.03119913e-04]),
 array([-1.02550722e+00,  1.21871948e-04]),
 array([-9.43466646e-01, -7.31231688e-05]),
 array([-8.67989314e-01,  4.38739013e-05]),
 array([-7.98550169e-01, -2.63243408e-05]),
 array([-7.34666155e-01,  1.57946045e-05]),
 array([-6.75892863e-01, -9.47676268e-06]),
 array([-6.21821434e-01,  5.68605761e-06]),
 array([-

### Bài 2 Gradient Descent + Momentum:

In [48]:
def df_w(W):
    # Unpack w1 and w2 from W
    w1, w2 = W

    # Compute partial derivatives
    dw1 = 0.2 * w1  # ∂f/∂w1
    dw2 = 4 * w2  # ∂f/∂w2

    # Create gradient array
    dW = np.array([dw1, dw2])

    return dW

In [49]:
def sgd_momentum(W, dW, lr, V, beta):
    V = beta*V + (1-beta)*dW
    W = W - lr*V

    return W, V

In [50]:
def train_p1(optimizer, lr, epochs, beta=0.9): # Added beta parameter with default value
    # initial
    W = np.array([-5, -2], dtype=np.float32)
    V = np.array([0, 0], dtype=np.float32)
    results = [W.copy()]

    for epoch in range(epochs):
        # Compute the gradient at the current point
        dW = df_w(W)  # Gradient calculation (assumes `df_w` is defined)

        # Update W and V using the optimizer, now passing beta
        W, V = optimizer(W, dW, lr, V, beta)

        # Store the updated W
        results.append(W.copy())

    return results

In [51]:
train_p1(sgd_momentum, lr=0.6, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.94, -1.52]),
 array([-4.82672, -0.7232 ]),
 array([-4.66684736,  0.167488  ]),
 array([-4.46695982,  0.92891008]),
 array([-4.23345751,  1.39125153]),
 array([-3.97250394,  1.47345847]),
 array([-3.68997568,  1.19381468]),
 array([-3.39142054,  0.65561975]),
 array([-3.08202387,  0.01389557]),
 array([-2.76658258, -0.56699113]),
 array([-2.44948643, -0.95371129]),
 array([-2.13470605, -1.07286872]),
 array([-1.82578724, -0.92262192]),
 array([-1.52585086, -0.56597054]),
 array([-1.23759791, -0.10915136]),
 array([-0.96331909,  0.32818222]),
 array([-0.70490831,  0.64301871]),
 array([-0.46387971,  0.77204706]),
 array([-0.24138742,  0.70288128]),
 array([-0.03824771,  0.47194058]),
 array([0.14503701, 0.1508282 ]),
 array([ 0.30825281, -0.17437171]),
 array([ 0.45144799, -0.42520241]),
 array([ 0.57490629, -0.54890147]),
 array([ 0.67911987, -0.52849427]),
 array([ 0.76476266, -0.38328916]),
 array([ 0.83266402, -0.16061517]),
 array([0.883

### Bài 3 RMSProp:

In [22]:
def df_w(W):
    # Unpack w1 and w2 from W
    w1, w2 = W

    # Compute partial derivatives
    dw1 = 0.2 * w1  # ∂f/∂w1
    dw2 = 4 * w2  # ∂f/∂w2

    # Create gradient array
    dW = np.array([dw1, dw2])

    return dW

In [23]:
def RMSProp(W, dW, lr, S, gamma):
    epsilon = 1e-6

    # Update the exponentially weighted average of squared gradients
    S = gamma * S + (1 - gamma) * (dW ** 2)

    # Update the weights using RMSProp formula
    W = W - lr * dW / (np.sqrt(S) + epsilon)

    return W, S

In [24]:
def train_p1(optimizer, lr, epochs):
    # Initial weights and moving averages
    W = np.array([-5, -2], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)  # Initialize moving averages to zero

    # Store results
    results = [W.copy()]

    # Optimization loop
    for epoch in range(epochs):
        # Compute gradients
        dW = df_w(W)  # Assuming `df_w` is defined to calculate gradients

        # Update weights and moving averages using the optimizer
        W, S = optimizer(W, dW, lr, S, gamma=0.9)  # Pass decay rate gamma (e.g., 0.9)

        # Store updated weights
        results.append(W.copy())

    return results

In [25]:
train_p1(RMSProp, lr=0.3, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.0513197 , -1.05131708]),
 array([-3.43519553, -0.59152376]),
 array([-2.95893489, -0.3294397 ]),
 array([-2.56546089, -0.17756504]),
 array([-2.22920358, -0.09163272]),
 array([-1.93626564, -0.04494508]),
 array([-1.67817504, -0.02081429]),
 array([-1.44934809, -0.00903562]),
 array([-1.24588029, -0.00364592]),
 array([-1.06490135, -0.00135352]),
 array([-9.04200650e-01, -4.56447225e-04]),
 array([-7.61994932e-01, -1.37563947e-04]),
 array([-6.36776983e-01, -3.62604278e-05]),
 array([-5.27213771e-01, -8.11346375e-06]),
 array([-4.32077091e-01, -1.47475425e-06]),
 array([-3.50197152e-01, -2.02787524e-07]),
 array([-2.80433359e-01, -1.84235524e-08]),
 array([-2.21658617e-01, -7.67771777e-10]),
 array([-1.72754375e-01,  7.80432778e-12]),
 array([-1.32614084e-01, -5.05777072e-13]),
 array([-1.00152823e-01,  6.19098174e-14]),
 array([-7.43209130e-02, -1.13368674e-14]),
 array([-5.41193712e-02,  2.80153177e-15]),
 array([-3.86152607e-02, -8.81296

### Bài 4 Adam:

In [26]:
def df_w(W):
    # Unpack w1 and w2 from W
    w1, w2 = W

    # Compute partial derivatives
    dw1 = 0.2 * w1  # ∂f/∂w1
    dw2 = 4 * w2  # ∂f/∂w2

    # Create gradient array
    dW = np.array([dw1, dw2])

    return dW

In [27]:
def Adam(W, dW, lr, V, S, beta1, beta2, t):
    epsilon = 1e-6

    # Update exponentially weighted averages
    V = beta1 * V + (1 - beta1) * dW
    S = beta2 * S + (1 - beta2) * (dW ** 2)

    # Compute bias-corrected first and second moments
    V_corrected = V / (1 - beta1 ** t)
    S_corrected = S / (1 - beta2 ** t)

    # Update weights
    W = W - lr * V_corrected / (np.sqrt(S_corrected) + epsilon)

    return W, V, S

In [33]:
def train_p1(optimizer, lr, epochs):
    # Initial values
    W = np.array([-5, -2], dtype=np.float32)
    V = np.array([0, 0], dtype=np.float32)  # First moment vector
    S = np.array([0, 0], dtype=np.float32)  # Second moment vector
    results = [W.copy()]

    # Optimization loop
    for t in range(1, epochs + 1):  # t starts at 1
        # Calculate gradient
        dW = df_w(W)  # Assuming `df_w` is defined elsewhere

        # Update weights using the optimizer
        W, V, S = optimizer(W, dW, lr, V, S, beta1=0.9, beta2=0.999, t=t)

        # Store updated weights
        results.append(W.copy())

    return results

In [34]:
train_p1(Adam, lr=0.2, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.8000002 , -1.80000002]),
 array([-4.60025478, -1.60082451]),
 array([-4.40094848, -1.40317262]),
 array([-4.20227764, -1.20787822]),
 array([-4.00445033, -1.01592745]),
 array([-3.80768638, -0.82847307]),
 array([-3.61221732, -0.64684159]),
 array([-3.41828623, -0.47252765]),
 array([-3.22614739, -0.30716934]),
 array([-3.03606592, -0.15249855]),
 array([-2.84831706, -0.01026326]),
 array([-2.66318543,  0.11787552]),
 array([-2.480964  ,  0.23046161]),
 array([-2.30195279,  0.3263587 ]),
 array([-2.12645742,  0.40484195]),
 array([-1.95478732,  0.46564961]),
 array([-1.7872537 ,  0.50898799]),
 array([-1.62416726,  0.53549442]),
 array([-1.46583566,  0.54617144]),
 array([-1.31256067,  0.54230812]),
 array([-1.16463526,  0.52540206]),
 array([-1.02234036,  0.4970906 ]),
 array([-0.88594163,  0.4590951 ]),
 array([-0.75568617,  0.41317781]),
 array([-0.63179919,  0.3611089 ]),
 array([-0.51448089,  0.30464048]),
 array([-0.40390346,  0.24548

### Bài 5 Vanishing Problem (Optional):

### Load Data:

In [52]:
!gdown 1y8xhCM_rVCgxOPSF3VtVkFxnwxtBlH0x

Downloading...
From (original): https://drive.google.com/uc?id=1y8xhCM_rVCgxOPSF3VtVkFxnwxtBlH0x
From (redirected): https://drive.google.com/uc?id=1y8xhCM_rVCgxOPSF3VtVkFxnwxtBlH0x&confirm=t&uuid=dda55826-6219-40d3-96d1-8a0f1c3269b5
To: /content/adopt.py
100% 18.3k/18.3k [00:00<00:00, 43.7MB/s]


In [53]:
import torch
from torch import nn
from adopt import ADOPT
from torch.utils.data import Dataset, DataLoader
import torchvision
from torchvision.datasets import FashionMNIST
import torchvision.transforms as transforms
import numpy as np
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
torch.manual_seed(42)

In [54]:
batch_size = 512
num_epochs = 300
lr = 0.001

In [55]:
train_dataset = FashionMNIST(root='./data', train=True, download=True, transform=transforms.ToTensor())
train_loader = DataLoader(train_dataset, batch_size, shuffle=True)
test_dataset = FashionMNIST(root='./data', train=False, download=True, transform=transforms.ToTensor())
test_loader = DataLoader(test_dataset, batch_size)

### Build và Compile Model

In [56]:
class MLP(nn.Module):
    def __init__(self, input_dims, hidden_dims, output_dims):
        super(MLP, self).__init__()
        self.layer1 = nn.Linear(input_dims, hidden_dims)
        self.layer2 = nn.Linear(hidden_dims, hidden_dims)
        self.layer3 = nn.Linear(hidden_dims, hidden_dims)
        self.layer4 = nn.Linear(hidden_dims, hidden_dims)
        self.layer5 = nn.Linear(hidden_dims, hidden_dims)
        self.output = nn.Linear(hidden_dims, output_dims)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = nn.Flatten()(x)
        x = self.layer1(x)
        x = self.sigmoid(x)
        x = self.layer2(x)
        x = self.sigmoid(x)
        x = self.layer3(x)
        x = self.sigmoid(x)
        x = self.layer4(x)
        x = self.sigmoid(x)
        x = self.layer5(x)
        x = self.sigmoid(x)
        out = self.output(x)
        return out

In [57]:
import torch.optim as optim

model = MLP(input_dims=784, hidden_dims=128, output_dims=10).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=lr)

In [ ]:
train_losses = []
train_acc = []
val_losses = []
val_acc = []
for epoch in range(num_epochs):
    model.train()
    t_loss = 0
    t_acc = 0
    cnt = 0
    for X, y in train_loader:
        X, y = X.to(device), y.to(device)
        optimizer.zero_grad()
        outputs = model(X)
        loss = criterion(outputs, y)
        loss.backward()
        optimizer.step()
        t_loss += loss.item()
        t_acc += (torch.argmax(outputs, 1) == y).sum().item()
        cnt += len(y)
    t_loss /= len(train_loader)
    train_losses.append(t_loss)
    t_acc /= cnt
    train_acc.append(t_acc)

    model.eval()
    v_loss = 0
    v_acc = 0
    cnt = 0
    with torch.no_grad():
        for X, y in test_loader:
            X, y = X.to(device), y.to(device)
            outputs = model(X)
            loss = criterion(outputs, y)
            v_loss += loss.item()
            v_acc += (torch.argmax(outputs, 1)==y).sum().item()
            cnt += len(y)
    v_loss /= len(test_loader)
    val_losses.append(v_loss)
    v_acc /= cnt
    val_acc.append(v_acc)
    print(f"Epoch {epoch+1}/{num_epochs}, Train_Loss: {t_loss:.4f}, Train_Acc: {t_acc:.4f}, Validation Loss: {v_loss:.4f}, Val_Acc: {v_acc:.4f}")